### ISSUE TITLE
base24 support

### ISSUE THREAD

**Issue by auroraanna** [Misterio77/nix-colors#25]
I said in another issue that the extra colors from base24 are missing in this project: https://github.com/Misterio77/nix-colors/issues/7#issuecomment-1037596734. Without the extra colors, using nix-colors would kind of be a downgrade for me. Can base24 support please be added? The colorschemes that are only base16 would not have to be made base24 of course.

**Comment by Misterio77** [comment]
Hello!

I'd love to get this implemented. Feel free to open up a PR if you have time, otherwise I might give it a shot soon(ish)

**Comment by Misterio77** [comment]
This should be fixed by https://github.com/Misterio77/nix-colors/pull/26
