### ISSUE TITLE
vim plugin usage is unavaialbe in vim, only in neovim

### ISSUE THREAD

**Issue by thecatwasnot** [Misterio77/nix-colors#27]
In home-manager, [programs.vim.plugins expects a package from vimPlugins](https://nix-community.github.io/home-manager/options.html#opt-programs.vim.plugins), neovim.plugins [will take a submodule](https://nix-community.github.io/home-manager/options.html#opt-programs.neovim.plugins) .
If you try to use this with vim.plugins, you'll get an error:
```
error: A definition for option `programs.vim.plugins."[definition 1-entry 2]"' is not of type `string or package'. Definition values:
       - In `/nix/store/ijy10wfrhv0iinskckx0wzp95igb5zcb-source/home-manager/cole/cli/vim.nix':
           {
             config = "colorscheme nix-material-darker";
             plugin = <derivation /nix/store/h3lr56hl0l5hi2bksaiabyx2v38d2lhx-nix-material-darker.vim.drv>;
           }
```
Documentation should make this clearer.  Happy to take any thoughts/suggestions and make a pr.

**Comment by Misterio77** [comment]
Hello,

Oh, yeah, this is a documentation program. I'll push a fix soonish

**Comment by thecatwasnot** [comment]
No problem really, just wanting to document the error/fix for folks confused like I was :slightly_smiling_face:
Thanks for all the work, helped me get nixos up and running as a desktop.
