### ISSUE TITLE
reconciliating nix-colors with transparency?

### ISSUE THREAD

**Issue by KiaraGrouwstra** [Misterio77/nix-colors#41]
i tried using nix-colors to swap out the theme for e.g. rofi, then realized that otherwise i might use `rgba` to also set a transparency value.
now, i'm not sure baking transparency into the color scheme (over application style) would make sense, as i suppose transparency isn't part of a color.
but then, what might be a good way to go about setting transparency while using nix-colors?

**Comment by Kyesarri** [comment]
CSS:
`background-color: #${config.colorScheme.colors.base01}FF;`

FF being the transparency 

Bit of a hacky manual method but it works for my configuration.

**Comment by KiaraGrouwstra** [comment]
thanks!
it looks like tinted-theming dealt with this by allowing to have the colors queried [separately](https://github.com/tinted-theming/base16-rofi/blob/master/templates/colors.mustache#L16), but the workaround def seems nicer.

**Comment by Misterio77** [comment]
Hey! Apologies for missing this issue.

If the `#RRGGBBAA` is not an option (or if you prefer decimal for whatever reason), you can use https://github.com/Misterio77/nix-colors/pull/18 's [conversion functions](https://github.com/Misterio77/nix-colors/blob/main/lib/core/conversions.nix).

```
nix-repl> nix-colors.lib.conversions.hexToRGB "000FFF"
[ 0 15 255 ]
```

For a CSS RGBA example:
```css
.foo {
    background-color: rgba(${hexToRGBString "," config.colorscheme.palette.base00},0.75);
}
```
