### ISSUE TITLE
hex to dec help

### ISSUE THREAD

**Issue by aspauldingcode** [Misterio77/nix-colors#60]
How can I do what I'm trying to do?

```
system.defaults.CustomUserPreferences = {
  NSGlobalDomain = {
    AppleHighlightColor = let
      # Example hex color code
      hexColor = "FF00FF";  # Replace with your hex color (without #)

      # Manually set RGB values
      rgbValues = [
        255
        0
        255
      ];
      
      # Normalize RGB values to 0-1 range
      r = builtins.elemAt rgbValues 0 / 255.0;
      g = builtins.elemAt rgbValues 1 / 255.0;
      b = builtins.elemAt rgbValues 2 / 255.0;
    in "${toString r} ${toString g} ${toString b} Other";
  };
};
```

I am expecting the hex to decimal to format as the following string:
`"1.0 0.5 1.0 Other";`

As r, g, b, "Other" string values.

so that I can basically do an `r g b` ranging from `0.0` to `1.0` custom color for macOS accent using nix darwin macos defaults configuration.

**Comment by aspauldingcode** [comment]
I found this
https://discourse.nixos.org/t/convert-hexadecimal-color-triplet-to-decimal/31633/2

and I'm not sure what to do with it.

I also found this
https://github.com/Misterio77/nix-colors/blob/main/lib/core/tests/conversions.nix

and 
https://github.com/Misterio77/nix-colors/blob/main/lib/core/conversions.nix

in the code idk what it is or how to use it...

**Comment by LateNightIceCream** [comment]
Hi! If I'm understanding you correctly I suggest using the function `hexToRGBString` in your own custom function:
```nix
myHexToRGB = hex: "${nix-colors.lib.conversions.hexToRGBString " " hex} Other";
```

So maybe use it like this:
```nix
system.defaults.CustomUserPreferences = 
let
  myHexToRGB = hex: "${nix-colors.lib.conversions.hexToRGBString " " hex} Other";
in
{
  NSGlobalDomain = {
    AppleHighlightColor = myHexToRGB "ff00ff";
  };
};
```

I'm unsure about how your config is structured or where your nix-colors comes from. But I hope this helps!

**Comment by fpiribauer** [comment]
I don't know anything about Mac but if you really need values from `0.0` to `1.0` something like this ought to do
```nix
let
  hexColor = "ea6962";
  hexColorConverted = builtins.toString (
    (builtins.map (x: x / 255.0) (nix-colors.lib.conversions.hexToRGB hexColor))
    ++ ["Others"]
  );
in
system.defaults.CustomUserPreferences = {
  NSGlobalDomain = {
    AppleHighlightColor = hexColorConverted;
  };
};
```
This will output the string `"0.917647 0.411765 0.384314 Others"`

**Comment by aspauldingcode** [comment]
This is beautiful.

Thank you!
I now can use darwin defaults command with nix-darwin and define macOS colors.

https://github.com/aspauldingcode/.dotfiles/blob/bfb021f759b0bd526ffbb0b3c4dbc605d1ab6468/system/NIXY/modules/darwin-defaults.nix#L244

https://github.com/aspauldingcode/.dotfiles/commit/bfb021f759b0bd526ffbb0b3c4dbc605d1ab6468
